services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/app          
      - /app/node_modules 
      - /app/.next   
    user: "1001:1001"    
    environment:
      NODE_ENV: development
      HOSTNAME: "0.0.0.0" 
    working_dir: /app
    command: ["npm", "run", "dev"] 
